### ISSUE TITLE
Error Unexpected token ' in JSON at position 21

### ISSUE THREAD

**Issue by TheTakeus** [mmd649/discord-music-bot#1]
**Hello

I have a problem with the bot configuartion,
I did everything as it should have been done in the readme file, discord js is already installed and ytp-core, ffmpeg, ...
when I execute the script node niga.js (to check if everything works before putting it in "pm2")
I have a mistake:**

SyntaxError: /home/pi/discord/2CB-N/config.json: Unexpected token ' in JSON at position 21
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/discord/2CB-N/naga.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
pi@Takeus-Server1:~/discord/2CB-N $ ^C

**Comment by mmd649** [comment]
Have you run 'npm install' so that all dependencies are installed?

**Comment by TheTakeus** [comment]
Yes

**Comment by mmd649** [comment]
The config.json file should be in the root directory of the bot. Where did you place it?

**Comment by TheTakeus** [comment]
In the same directory of the bot

**Comment by mmd649** [comment]
Can you just double check your config.json file that you have filled it in correctly. From the error you got, it seems like somewhere in there, there is an 'unexpected token'.
`
{
    "yt_api_key": 'your youtube api key here',
    "bot_token": 'your discord bot token here',
    "prefix": 'what prefix you want',
    "op": 'your discord id',
    "weather_api": ''
}
`

**Comment by TheTakeus** [comment]
I've got the same thing you've got.
![Capture](https://user-images.githubusercontent.com/59620737/71986719-360d9b80-322d-11ea-9a8a-96c6d95f1e3d.PNG)

**Comment by mmd649** [comment]
Add this 
"weather_api": ''
You dont have to fill it in if you dont plan to use the weather command. Just need to have that in.

**Comment by mmd649** [comment]
I actually tried to leave the weather_api in mine and it still works. From the error you provided earlier it seems to be a random ' in your json.config

**Comment by TheTakeus** [comment]
this doesn't change anything when I removed(weather api), I don't understand where is the problem

**Comment by mmd649** [comment]
Sorry about the inconvenience, I mistyped the configuration in the readme. The values should be between a double qoutes instead of single quotes. So change it to

{
"yt_api_key": "your youtube api key here",
"bot_token": "your discord bot token here",
"prefix": "what prefix you want",
"op": "your discord id"
}

**Comment by TheTakeus** [comment]
Thanks, i have a new error after this:

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/pi/discord/2CB-N/niga.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by TheTakeus** [comment]
We advance, the bot is launched but nothing on discord (the bot remains deco) and then I have this error ...

To test the bot I launch it with node ...
The error 
pi@Takeus-Server1:~/discord/2CB-N $ node naga.js
Naga is now online.
(node:32114) UnhandledPromiseRejectionWarning: MongooseTimeoutError: Server selection timed out after 30000 ms
    at new MongooseTimeoutError (/home/pi/discord/2CB-N/node_modules/mongoose/lib/error/timeout.js:22:11)
    at NativeConnection.Connection.openUri (/home/pi/discord/2CB-N/node_modules/mongoose/lib/connection.js:763:19)
    at Mongoose.connect (/home/pi/discord/2CB-N/node_modules/mongoose/lib/index.js:332:15)
    at Object.<anonymous> (/home/pi/discord/2CB-N/naga.js:8:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TheTakeus** [comment]
And i have not 3000ms of lattency, i have fiber and my rpi is connected to the box , the ping of my other bot (in the same rpi) has :
![BCDC2E12-ED0D-45EA-92B1-CE46E1264B57](https://user-images.githubusercontent.com/59620737/72014558-63c00800-3260-11ea-80f6-64ff9789ba7c.jpeg)

**Comment by mmd649** [comment]
The error you have is because of the Database connection(Mongoose). I'm assuming you dont have MongoDB installed on your pc. Try installing this https://www.mongodb.com/download-center/community since this is the database used for storing the playlists created.

**Comment by TheTakeus** [comment]
Ok, i try it tomorrow, thanks you

**Comment by TheTakeus** [comment]
The same error, i have installed mongodp and i use for start:
![Capture](https://user-images.githubusercontent.com/59620737/72046499-d2c94b00-32b8-11ea-88f0-4100530faca8.PNG)

The Error:

`pi@Takeus-Server1:~/discord/2CB-N $ node naga.js
Naga is now online.
(node:25359) UnhandledPromiseRejectionWarning: MongooseTimeoutError: Server selection timed out after 30000 ms
    at new MongooseTimeoutError (/home/pi/discord/2CB-N/node_modules/mongoose/lib/error/timeout.js:22:11)
    at NativeConnection.Connection.openUri (/home/pi/discord/2CB-N/node_modules/mongoose/lib/connection.js:763:19)
    at Mongoose.connect (/home/pi/discord/2CB-N/node_modules/mongoose/lib/index.js:332:15)
    at Object.<anonymous> (/home/pi/discord/2CB-N/naga.js:8:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:25359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

**Comment by mmd649** [comment]
I am using windows for my OS and to configure Mongodb, you need to create a folder called data in C:. Inside the data folder you then create another folder called db. 

https://www.youtube.com/watch?v=FwMwO8pXfq0 is a good step by step installation and configuration tutorial. I highly suggest you watch it and see if that would help.

**Comment by TheTakeus** [comment]
.db or db. 
(name of the file ?)

**Comment by TheTakeus** [comment]
I think to search a other music bot ...
too many problems, too many prerequisites (don't even specify) ...

**Comment by mmd649** [comment]
Sorry about the inconvenience you've faced. I just thought that most people would already have an existing database (sql/mongo) already installed on their pc.
